cartapp/urls.py
from django.urls import path
from .views import cart_add,cart_detail,cart_remove

app_name= "cartapp"
'''
This line sets a namespace for the URLs defined in this module. By using app_name, you can refer to these URLs in templates and other parts of your Django project with a prefix (e.g., cartapp:cart_add). This helps avoid naming conflicts when you have multiple apps with similar URL names.
'''

urlpatterns = [
    path('add/<int:product_id>/',cart_add,name="cart_add"),#path name cart_add,<int:product_id> means we're passing product id
    path("",cart_detail,name="cart_detail"),
    path("remove/<int:product_id>/",cart_remove,name="remove_item")
]

'''
(1)path('add/<int:product_id>/', cart_add, name="cart_add"),

The URL pattern add/<int:product_id>/ specifies that this route will handle requests to /add/ followed by an integer representing the product ID (e.g., 127.0.0.1:8000/add/5/).

URL: /add/<product_id>/
Purpose: Calls the cart_add view when a user adds a product to the cart.
Dynamic Parameter: <int:product_id> captures the product's ID and passes it to the cart_add view.
Name: cart_add — used for referencing this URL.


(2)path("", cart_detail, name="cart_detail"),

URL Pattern: The empty string "" means this route will handle requests to the root URL of this app (e.g., /cart/).
View Function: It calls the cart_detail view function when accessed.
Name: cart_detail — used for referencing this URL.

(3)path("remove/<int:product_id>/", cart_remove, name="remove_item")

URL Pattern: The pattern remove/<int:product_id>/ specifies that this route will handle requests to /remove/ followed by an integer (the product ID) (e.g., /remove/5/).

View Function: It calls the cart_remove view function when accessed.

Name: remove_item — used for referencing this URL.
'''

ecomproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

# Django usually checks the URL pattern in the order that they r 
# defined , so it check the cartapp.urls before the storeapp.urls
app_name = "cartapp"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/',include('cartapp.urls')),
    path('',include('storeapp.urls')),
    path('ordersapp/',include('ordersapp.urls'))
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

storeapp/urls.py
from django.urls import path
from . import views

app_name = 'storeapp'  # Register the namespace

urlpatterns = [
    #Leave as empty string for base url(home page)
    #path('',views.main,name='main.html'),#main.html is the homepage
    # path('',views.list,name="list.html"),
    # path('list/',views.list,name="list.html"),
    # path('detail/',views.detail,name="detail.html"),

    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('product/<int:id>/<slug:slug>/', views.product_detail, name="product_detail"),
]

templates/cart.html
{% extends 'main.html' %}
{% load static %}


{% block content %}
     <h3>Cart</h3>
{% endblock content %}

templates/checkout.html
{% extends 'main.html' %}
{% load static %}

{% block content %}
     <h3>checkout</h3>
{% endblock content %}

templates/detail.html
<!-- This detail.html is created for every product individual detail ,when customer click on each product name like (shirt1,shirt2) then they will able to see each product details  -->

{% extends 'main.html' %}
{% block title %}{{product.name}}{% endblock %}
{% block content %}
<div class="container mx-auto p-4 flex">

    <div>
        {%if product.image%}
        <img src="{{product.image.url}}" alt={{product.name}} class="max-h-[60vh]">
        {%else%}
        <p>The image is not available</p>
        {%endif%}
        <h3 class="font-semibold">{{product.name}}</h3>
        <p>{{product.description}}</p>
        <p class="text-indigo-600">${{product.price}}</p>
        
        <form action="{%url 'cartapp:cart_add' product.id%}"method="post" id="add-to-cart-form">
            {%csrf_token%}
            <button type="submit" class="bg-indigo-600 text-white px-4 py-2 rounded">Add to cart</button>
        <p id="message"></p>
        </form>
        
    
    </div>
</div>
<script>
    document.getElementById('add-to-cart-form').addEventListener("submit", function(event){
        event.preventDefault();

        const form = event.target;
        const url = form.action;
        const formData = new FormData(form);

        fetch(url, {
            method:'POST',
            headers:{
                'X-CSRFToken':formData.get('csrfmiddlewaretoken')
            },
            body: formData
        })
        .then(response => response.json())
        .then(data=>{
            const messageElement = document.getElementById('message');
            if (data.success){
                messageElement.textContent = data.message;
            }else{
                message.textContent = "Failed to add to cart";
            }
        })
        .catch(error=>{
            console.error("Error", error);
        })
    })
</script>
{% endblock %}

templates/list.html
{% extends 'main.html' %}
{% block content %}
<div class="container mx-auto p-4 flex">
    <aside class="w-1/4 p-4">
    <h2 class="font-bold">Categories :</h2>
    <ul>
        {% for category in categories %}
        <li>
            <!-- from urls.py, we've to add category_slug for product list of category  -->
            <a href="{% url 'storeapp:product_list_by_category' category.slug %}">{{category.name}}</a>
        </li>
        {% endfor %}
    </ul>
    </aside>
    <main class="w-3/4 p-4">
        
        {%if category%} <!-- if category is seleted by user -->
        <h2 class="font-bold mb-4">{{category.name}}</h2>
        
        {%else%} <!-- if no category is seleted by user -->
        <h2 class="font-bold mb-4">All Products:</h2>

        {%endif%}
        <div class="grid grid-cols-4 gap-4">
            {% for product in products %}
            <a href="{% url 'storeapp:product_detail' product.id product.slug %}"><!-- from urls.py of app, what we've to pass here product.id and product.slug  -->
            <div>
                
                {% if product.image %}<!-- if the choosen product has an image  -->
                <img src="{{product.image.url}}" alt={{product.name}} class="h-30 w-30 object-cover">
                {%else%}
                <p>The image is not available</p>
                {%endif%}

                <h3 class="font-semibold">{{product.name}}</h3>
                <p>{{product.description}}</p>
                <p class="text-indigo-600">${{product.price}}</p>
            </div>
        </a>
            {%endfor%}

        </div>
    </main>
</div>
{% endblock %}

templates/main.html
<!-- base.html of piko -->
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,  initial-scale=1">
    <link rel="stylesheet" href="{% static 'output.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" />
    <title>Shop site</title>
    <link rel="icon" href="favicon.png">
</head>
<body class="bg-gray-200 flex flex-col min-h-screen">
<header class="shadow-md">
        {% include "nav.html" %}
</header>

<main class="container mx-auto py=8 flex-grow">
        {% block content %}
        {% endblock content %}
</main>


<footer>
    <div class="container mx-auto p-4 text-center">
        <p>@2024 E-Com Inc. All rights reserved.</p>
    </div>
</footer>



</body>
</html>

templates/nav.html
<nav class="container mx-auto p-4 flex justify-between items-center">
    <a href='/' class="text-2xl font-bold text-indigo-600">E-Com</a>

<a href="{% url 'cartapp:cart_detail' %}">
    <svg class="w-8" version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 width="40px" height="36px" viewBox="0 0 40 36" style="enable-background:new 0 0 40 36;" xml:space="preserve">
<g id="Page-1_4_" sketch:type="MSPage">
	<g id="Desktop_4_" transform="translate(-84.000000, -410.000000)" sketch:type="MSArtboardGroup">
		<path id="Cart" sketch:type="MSShapeGroup" class="st0" d="M94.5,434.6h24.8l4.7-15.7H92.2l-1.3-8.9H84v4.8h3.1l3.7,27.8h0.1
			c0,1.9,1.8,3.4,3.9,3.4c2.2,0,3.9-1.5,3.9-3.4h12.8c0,1.9,1.8,3.4,3.9,3.4c2.2,0,3.9-1.5,3.9-3.4h1.7v-3.9l-25.8-0.1L94.5,434.6"
			/>
	</g>
</g>
  </svg>
</a>
</nav>